export interface Country {
  country: string;
  code: string;
}

export const countries: Country[] = [
  { country: "Albania", code: "AL" },
  { country: "Andorra", code: "AD" },
  { country: "Argentina", code: "AR" },
  { country: "Australia", code: "AU" },
  { country: "Austria", code: "AT" },
  { country: "Bahamas", code: "BS" },
  { country: "Barbados", code: "BB" },
  { country: "Belgium", code: "BE" },
  { country: "Belize", code: "BZ" },
  { country: "Bosnia and Herzegovina", code: "BA" },
  { country: "Brazil", code: "BR" },
  { country: "Bulgaria", code: "BG" },
  { country: "Canada", code: "CA" },
  { country: "Cayman Islands", code: "KY" },
  { country: "Chile", code: "CL" },
  { country: "China", code: "CN" },
  { country: "Croatia", code: "HR" },
  { country: "Cyprus", code: "CY" },
  { country: "Czech Republic", code: "CZ" },
  { country: "Denmark", code: "DK" },
  { country: "El Salvador", code: "SV" },
  { country: "Estonia", code: "EE" },
  { country: "Faroe Islands", code: "FO" },
  { country: "Finland", code: "FI" },
  { country: "France", code: "FR" },
  { country: "Germany", code: "DE" },
  { country: "Gibraltar", code: "GI" },
  { country: "Greece", code: "GR" },
  { country: "Grenada", code: "GD" },
  { country: "Guyana", code: "GY" },
  { country: "Hong Kong", code: "HK" },
  { country: "Hungary", code: "HU" },
  { country: "Iceland", code: "IS" },
  { country: "Ireland", code: "IE" },
  { country: "Israel", code: "IL" },
  { country: "Italy", code: "IT" },
  { country: "Japan", code: "JP" },
  { country: "Latvia", code: "LV" },
  { country: "Liechtenstein", code: "LI" },
  { country: "Lithuania", code: "LT" },
  { country: "Luxembourg", code: "LU" },
  { country: "Macau", code: "MO" },
  { country: "Malaysia", code: "MY" },
  { country: "Malta", code: "MT" },
  { country: "Monaco", code: "MC" },
  { country: "Montenegro", code: "ME" },
  { country: "Morocco", code: "MA" },
  { country: "Netherlands", code: "NL" },
  { country: "New Zealand", code: "NZ" },
  { country: "North Macedonia", code: "MK" },
  { country: "Norway", code: "NO" },
  { country: "Philippines", code: "PH" },
  { country: "Poland", code: "PL" },
  { country: "Portugal", code: "PT" },
  { country: "Romania", code: "RO" },
  { country: "Russia", code: "RU" },
  { country: "Saint Lucia", code: "LC" },
  { country: "San Marino", code: "SM" },
  { country: "Serbia", code: "RS" },
  { country: "Singapore", code: "SG" },
  { country: "Slovakia", code: "SK" },
  { country: "Slovenia", code: "SI" },
  { country: "South Korea", code: "KR" },
  { country: "Spain", code: "ES" },
  { country: "Sweden", code: "SE" },
  { country: "Switzerland", code: "CH" },
  { country: "Taiwan", code: "TW" },
  { country: "Ukraine", code: "UA" },
  { country: "United Kingdom", code: "GB" },
  { country: "United States", code: "US" },
  { country: "Vatican City", code: "VA" }
];

export function getCountryCodes(): string[] {
  return countries.map(country => country.code);
}
